SET NAMES UTF8;
DROP DATABASE IF EXISTS tpp;
CREATE DATABASE tpp CHARSET=UTF8;
USE tpp;
CREATE TABLE tpp_user(
    uid INT PRIMARY KEY AUTO_INCREMENT,
	uname VARCHAR(32) UNIQUE NOT NULL,
	upwd VARCHAR(32),
	user_name VARCHAR(32)
);
INSERT INTO tpp_user VALUES(NULL,'ken','123456','KenWu');